### ISSUE TITLE
Windows defender flags steamlauncher 0.0.6.exe

### ISSUE THREAD

**Issue by DVT7121** [Sak32009/SteamLauncher#101]
Hello,

I downloaded 0.0.6 steamlauncher-0.0.6-win-x64-installer.exe. Windows defender said its a threat. I tried the portable installer and windows defender said nothing even with a scan on the portable folder. Windows defender gave me info to this,
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fUlthar.A!ml&threatid=2147751837.

**Comment by Sak32009** [comment]
It's a false positive on the installer and it's a bug of electron-builder.

It is not possible to solve at the moment.
