### ISSUE TITLE
Additional comments!

### ISSUE THREAD

**Issue by Soi9x** [Sak32009/SteamLauncher#11]
Hello the creator of this source code , many thanks for that , but I would like to comment more on the feature when I have just experienced your version , should add the lobby connection feature aka lobby , that will help very cool, thanks

**Comment by Sak32009** [comment]
"lobby feature" is not a feature of the launcher but of the emulator.

Send a request to the author of the emulator.

https://gitlab.com/Mr_Goldberg/goldberg_emulator

**Comment by Sak32009** [comment]
closed due to inactivity
