### ISSUE TITLE
Create disable_lan_only.txt next to steamclient64.dll

### ISSUE THREAD

**Issue by detiam** [Sak32009/SteamLauncher#152]
The experimental version of emu has a feature called "LAN only connections" which blocked all connection from internet.

It cause problem when using onlinefix's cracks or do anything that required networks, create disable_lan_only.txt next to steamclient64.dll can solve it.

So add a setting in game's profile in order to manage it? the file isn't in "steam_settings" folder, and better to manage pre game.

**Comment by Sak32009** [comment]
I don't use the experimental version with CPY support, but the experimental client version.
When you launch a game, is the SteamLauncher in offline mode?

**Comment by detiam** [comment]
but according to the readme :

> This is a build of the experimental version of my emu in steamclient mode with an included loader. See both the regular and experimental readmes for how to configure it.

SteamLauncher is in online mode, after create disable_lan_only.txt network works right a way (even in offline mode), if I delete the file network lost again.
btw the game is 1109570

**Comment by Sak32009** [comment]
OK! I got it :)
I will implement it as soon as possible.
Thank you!
