### ISSUE TITLE
incorrect "open save location"

### ISSUE THREAD

**Issue by detiam** [Sak32009/SteamLauncher#155]
steamlaunch will open save folder inside "steam_saves" even only "achievements.json" in it, while the actually save is stored in "steam_cloud" folder. isn't "steam_cloud" should be primary?

btw do you know a software called Depot Downloader, that one can download game file form steam using shared depot key?

**Comment by Sak32009** [comment]
1) fixed :)

2) no sorry

**Comment by detiam** [comment]
@Sak32009 
1. :D
2. Why sorry, just a thought. something like steamlite dose or TINserver? xD <br /> But maybe too much anyway.

**Comment by Sak32009** [comment]
I guess I did not understand the question, what is the idea?

**Comment by detiam** [comment]
@Sak32009 
The tool over there https://github.com/SteamRE/DepotDownloader can download games in you steam account direct form steam's server if you own it, and even update games. so just like official steam client or steamlite right?

And over there https://github.com/Lanzador/DepotDownloader is a fork that allow you to download games from steam's server even you don't own it at all.. just need a depotkey that can get by using (https://steamdb.info/tokendumper/). That is very interesting to me XD

So the idea is if you can integrate DepotDownloader in to Steamlauncher, it will be possible to install&updata games from steam with beautiful interface whlie don't own it XXD

## And BTW don't know why https://cs.rin.ru/forum/viewtopic.php?f=24&t=118435 Christsnatcher don't like it, probably because this will harm the positivity for people to uploading game's files? don't mention it on forum anyway...

**Comment by Sak32009** [comment]
for the moment I "suspend" the proposal, I will verify
