### ISSUE TITLE
Show "not successful" notification after success manually backup

### ISSUE THREAD

**Issue by detiam** [Sak32009/SteamLauncher#168]
![Honeycam 2022-05-22 06-13-57](https://user-images.githubusercontent.com/44510779/169670617-146ac545-e9bb-4cbe-a2e1-307e97162e89.gif)
Custom games that set in Ludusavi will cause this issue.

and shouldn't there have an option allowed to disable ludusavi function for games that already work with `goldberg_emulator`'s cloud save function.

**Comment by Sak32009** [comment]
could you tell me a game that saves in the emulator folder?

**Comment by detiam** [comment]
> could you tell me a game that saves in the emulator folder?

[Touhou Mystia's Izakaya](https://store.steampowered.com/app/1584090) saves in both emulator folder and appdata folder.

[DiRT 4](https://store.steampowered.com/app/421020) only saves in emulator folder.
