### ISSUE TITLE
Portable - SteamLauncher in AppData/Roaming

### ISSUE THREAD

**Issue by Mitch037** [Sak32009/SteamLauncher#182]
There is a SteamLauncher folder (with some content) in Windows' User AppData/Roaming directory when using the portable version. Would it be possible to keep that data inside the original portable SteamLauncher directory?

**Comment by Sak32009** [comment]
No, unfortunately this is not possible, however those data are irrelevant for the proper functioning of SteamLauncher. Mostly they only serve to speed up startup :)
