### ISSUE TITLE
prompt ""Couldn't find the requested Exe file. 找不到请求的exe文件。""

### ISSUE THREAD

**Issue by sherlockHlb** [Sak32009/SteamLauncher#83]
![image](https://user-images.githubusercontent.com/30238046/150503702-0e7b5f6a-2c6b-42b8-9286-95f08778af75.png)

**Comment by Sak32009** [comment]
There is currently no debugging system, I will implement it in later versions.

After you start the game and this error appears, go to "data/emulator/" inside the launcher folder and paste the content of ColdClientLoader.ini here.

**Comment by Sak32009** [comment]
closed due to inactivity
