### ISSUE TITLE
Cannot add exe in 0.0.3 - Blank console window

### ISSUE THREAD

**Issue by Oscillate18** [Sak32009/SteamLauncher#97]
Updated to the latest version with a fresh install and whenever I attempt to add an exe a blank console window appears and nothing further happens. I left this for a few mins and nothing.

![Screenshot 2022-02-20 111922](https://user-images.githubusercontent.com/65877846/154840104-18aa0eb0-aad0-44ea-9dae-be97118fa431.png)

**Comment by Sak32009** [comment]
Go to "%APPDATA%/SteamLauncher/logs" and post main.log
