### ISSUE TITLE
Could you add the ability to manually change steamid?

### ISSUE THREAD

**Issue by detiam** [Sak32009/SteamLauncher#99]
When i upgrade SteamLauncher to 0.0.3 though installer it required me to create another account, and the auto configured *steamid* was changed. Because that my achievements progress of ***Achievement Watcher*** is broken right now. How can i manually change it back ?

**Comment by Sak32009** [comment]
I planned to add in version 0.0.4 the possibility to modify the steamid directly from the launcher. Currently you can do this by going to the "%APPDATA%/SteamLauncher" folder and editing config.json manually

**Comment by detiam** [comment]
ok, thanks
